spring.application.name=webmessaging
spring.jpa.hibernate.ddl-auto=update
spring.datasource.url=jdbc:postgresql://localhost:5432/webmessaging
spring.datasource.username=webmessaging
spring.datasource.password=webmessaging
server.port=9090